version: '3.8'
services:

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" 
    restart: always 
#   app: 
#     build: .
#     depends_on:
#     - redis
#     ports: 
#     - "3333:3333"
#     networks:
#     - integration-goo-network
#     volumes: 
#     - .:/app:cached 
#     restart: always

# networks:
#  integration-goo-network:
#   driver: bridge