const AssignLabel = {"body":{"type":"object","properties":{"instanceId":{"type":"string","description":"Código da instância"},"leadId":{"type":"string","description":"ID do lead"},"labelId":{"type":"string","description":"ID do label"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const CreateCopyCopy = {"body":{"type":"object","required":["instanceId","departmentId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"departmentId":{"type":"string","description":"Id do departamento"},"name":{"type":"string","description":"Nome do departamento"},"welcomeMessage":{"type":"string","description":"Mensagem de boas vindas que será enviada quando um cliente é enviado para o departamento"},"endingTag":{"type":"string","description":"Id do motivo de finalização quando uma sessão for enviado para o departamento, será finalizada automaticamente"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const DepartmentsCreate = {"body":{"type":"object","required":["instanceId","name"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"name":{"type":"string","description":"Nome do departamento"},"welcomeMessage":{"type":"string","description":"Mensagem de boas vindas que será enviada quando um cliente é enviado para o departamento"},"endingTag":{"type":"string","description":"Id do motivo de finalização quando uma sessão for enviado para o departamento, será finalizada automaticamente"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const DepartmentsGetdepartmentbyid = {"body":{"type":"object","required":["instanceId","departmentId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"departmentId":{"type":"string","description":"Id do departamento"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const DepartmentsGetusersindepartment = {"body":{"type":"object","required":["instanceId","departmentId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"departmentId":{"type":"string","description":"Id do departamento"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const DepartmentsList = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const EditUser = {"body":{"type":"object","required":["instanceId","userId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"userId":{"type":"string","description":"Id do usuário"},"role":{"type":"string","description":"O tipo de usuário da instância"},"name":{"type":"string","description":"Nome do usuário"},"publicDepartment":{"type":"boolean","description":"Acesso aos departamentos públicos","default":false},"closedSessions":{"type":"boolean","description":"Acesso as sessões fechadas","default":false},"deleteMessage":{"type":"boolean","description":"Permissão para deletar uma mensagem enviada","default":false},"active":{"type":"boolean","description":"Status do usuário na instância","default":true}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const EndingsCreate = {"body":{"type":"object","required":["instanceId","name"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"name":{"type":"string","description":"Nome do motivo de finalização"},"message":{"type":"string","description":"Mensagem que será enviada automaticamente ao finalizar uma sessão"},"npsOverride":{"type":"string","description":"Opção de envio do NPS","default":"default"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const EndingsGetendingbyid = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"endingId":{"type":"string","description":"Id do motivo de finalização"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const EndingsList = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const EndingsUpdate = {"body":{"type":"object","required":["instanceId","endingId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"endingId":{"type":"string","description":"Id do motivo de finalização"},"name":{"type":"string","description":"Nome do motivo de finalização"},"message":{"type":"string","description":"Mensagem que será enviada automaticamente ao finalizar uma sessão"},"npsOverride":{"type":"string","description":"Opção de envio do NPS"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const GetAllUsersByInstance = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"active":{"type":"boolean","description":"Status do usuário se está ativo na instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const GetOrCreateSessionByNumber = {"body":{"type":"object","required":["instanceId","provider","number"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"provider":{"type":"string","description":"Provider de envio, ex.: cloud"},"number":{"type":"string","description":"Número de telefone do lead"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const GetTemplates = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const GetUserById = {"body":{"type":"object","required":["instanceId","userId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"userId":{"type":"string","description":"Id do usuário"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const HistoryReport = {"metadata":{"allOf":[{"type":"object","properties":{"token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Chave de acesso obtida no menu `Desenvolvedor`"},"date":{"type":"string","format":"date","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Data a exportar (ex: `2024-12-30`)"},"instanceId":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#","description":"Id da instância (ex: `chatpro-12345678`)"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const LeadsCreate = {"body":{"type":"object","required":["instanceId","number"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"number":{"type":"string","description":"Telefone do lead"},"name":{"type":"string","description":"Nome personalizado do lead"},"metadata":{"type":"string","description":"Informações adicionais"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const LeadsFindbyid = {"body":{"type":"object","required":["instanceId","leadId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"leadId":{"type":"string","description":"Id do lead"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const LeadsFindbyphonenumber = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"phoneNumber":{"type":"string","description":"Número de telefone do lead"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const LeadsFindlabels = {"body":{"type":"object","required":["instanceId","leadId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"leadId":{"type":"string","description":"Id do lead"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const LeadsUpdate = {"body":{"type":"object","required":["instanceId","leadId","name"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"leadId":{"type":"string","description":"Id do lead"},"name":{"type":"string","description":"Nome personalizado"},"metadata":{"type":"string","description":"Informações adicionais"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const MessagesGetall = {"body":{"type":"object","required":["instanceId","sessionId","limit","offset"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"fromMe":{"type":"boolean","description":"Quem enviou a mensagem"},"limit":{"type":"integer","format":"int32","minimum":-2147483648,"maximum":2147483647},"offset":{"type":"integer","format":"int32","minimum":-2147483648,"maximum":2147483647}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const MessagesReadmessages = {"body":{"type":"object","required":["instanceId","sessionId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const MessagesSendcontact = {"body":{"type":"object","required":["instanceId","sessionId","provider","contactName","contactNumber"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"provider":{"type":"string","description":"Provider de envio, ex.: cloud"},"contactName":{"type":"string","description":"Nome do contato"},"contactNumber":{"type":"string","description":"Número de telefone do contato"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const MessagesSendfilefromurl = {"body":{"type":"object","required":["instanceId","sessionId","url","provider"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"url":{"type":"string","description":"URL do arquivo"},"provider":{"type":"string","description":"Provider de envio, ex.: cloud"},"caption":{"type":"string","description":"Para o envio de imagens e documentos pode adicionar uma descrição que será enviada abaixo do arquivo"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const MessagesSendmessage = {"body":{"type":"object","required":["instanceId","sessionId","provider","message"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"provider":{"type":"string","description":"Provider de envio, ex.: cloud"},"message":{"type":"string","description":"Texto da mensagem a ser enviado"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const Register = {"body":{"type":"object","required":["instanceId","apiVersion","apiToken","wabaId","phoneId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"apiVersion":{"type":"string","description":"Versão da API da Meta"},"apiToken":{"type":"string","description":"Token permanente da Meta"},"wabaId":{"type":"string","description":"Id de identificação da Meta"},"phoneId":{"type":"string","description":"Id do telefone cadastrado na Meta"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SendTemplate = {"body":{"type":"object","required":["instanceId","number","name","languageCode"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"number":{"type":"string","description":"Telefone para envio"},"name":{"type":"string","description":"Nome do template"},"languageCode":{"type":"string","description":"Código da linguagem cadastrado no template, ex.: en"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SessionsAssigndepartment = {"body":{"type":"object","required":["instanceId","sessionId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"department_id":{"type":"string","description":"Id do departamento"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SessionsAssignto = {"body":{"type":"object","required":["instanceId","sessionId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"userId":{"type":"string","description":"Id do usuário da instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SessionsFinish = {"body":{"type":"object","required":["instanceId","sessionId","endingId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"},"endingId":{"type":"string","description":"Id do motivo de finalização"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SessionsGetsessionbyid = {"body":{"type":"object","required":["instanceId","sessionId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"sessionId":{"type":"string","description":"Id da sessão"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SessionsList = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"open":{"type":"boolean","description":"Status da sessão, ex.: open = false, buscará apenas as sessões finalizadas"},"start":{"type":"string","description":"Data inicial da busca, ex.: 2024-03-23T18:48:30.816008+01:00"},"end":{"type":"string","description":"Data final da busca, ex.: 2024-03-23T18:48:30.816008+01:00"},"endingTag":{"type":"string","description":"Id do motivo de finalização"},"userId":{"type":"string","description":"Id de um usuário da instância"},"departmentId":{"type":"string","description":"Id de um departamento da instância"},"leadId":{"type":"string","description":"Id de um lead"},"limit":{"type":"integer","format":"int32","minimum":-2147483648,"maximum":2147483647},"offset":{"type":"integer","format":"int32","minimum":-2147483648,"maximum":2147483647}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const SessionsListfromlead = {"body":{"type":"object","required":["instanceId","leadId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"leadId":{"type":"string","description":"Id do lead"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const ShortcutsCreate = {"body":{"type":"object","required":["instanceId","tag_id","type"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"tag_id":{"type":"string","description":"Tag de identificação da resposta rápida, ex.: mensagem_de_boas_vindas"},"type":{"type":"string","description":"Os tipos disponíveis são: text, image, document e audio"},"text":{"type":"string","description":"Texto que será enviado ao selecionar a resposta rápida, ex.: Bem vindo(a) ao chatPro!"},"desc":{"type":"string","description":"Para o envio de imagens e documentos pode adicionar uma descrição que será enviada abaixo do arquivo"},"url":{"type":"string","description":"Url da imagem, áudio ou documento"},"file_type":{"type":"string","description":"Tipo do arquivo enviado, ex.: image"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const ShortcutsDelete = {"body":{"type":"object","required":["instanceId","shortcutId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"shortcutId":{"type":"string","description":"Id da resposta rápida"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const ShortcutsGetShortcutById = {"body":{"type":"object","required":["instanceId","shortcutId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"shortcutId":{"type":"string","description":"Id da resposta rápida"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const ShortcutsList = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const ShortcutsUpdate = {"body":{"type":"object","required":["instanceId","shortcutId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"shortcutId":{"type":"string","description":"Id da resposta rápida"},"tag_id":{"type":"string","description":"Tag de identificação da resposta rápida, ex.: mensagem_de_boas_vindas"},"type":{"type":"string","description":"Os tipos disponíveis são: text, image, document e audio"},"text":{"type":"string","description":"Texto que será enviado ao selecionar a resposta rápida, ex.: Bem vindo(a) ao chatPro!"},"desc":{"type":"string","description":"Para o envio de imagens e documentos pode adicionar uma descrição que será enviada abaixo do arquivo"},"file_type":{"type":"string","description":"Tipo do arquivo enviado, ex.: image"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const TagsCreate = {"body":{"type":"object","required":["instanceId","name","color"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"name":{"type":"string","description":"Nome da etiqueta"},"color":{"type":"string","description":"Cor da etiqueta em hexadecimal, ex.: #089186"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const TagsGettagbyid = {"body":{"type":"object","required":["instanceId","tagId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"tagId":{"type":"string","description":"Id da etiqueta"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const TagsListleadsbytag = {"body":{"type":"object","required":["instanceId","tagId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"tagId":{"type":"string","description":"Id da etiqueta"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const TagsUpdate = {"body":{"type":"object","required":["instanceId","tagId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"tagId":{"type":"string","description":"Id da etiqueta"},"name":{"type":"string","description":"Nome da etiqueta"},"color":{"type":"string","description":"Cor da etiqueta em hexadecimal, ex.: #089186"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const UnassignLabel = {"body":{"type":"object","properties":{"instanceId":{"type":"string","description":"Código da instância"},"leadId":{"type":"string","description":"ID do lead"},"labelId":{"type":"string","description":"ID do label"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const UpdateOwner = {"body":{"type":"object","required":["instanceId","leadId","ownerId"],"properties":{"instanceId":{"type":"string"},"leadId":{"type":"string"},"ownerId":{"type":"string"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const WidgetsCreate = {"body":{"type":"object","required":["instanceId","name","number"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"name":{"type":"string","description":"Nome do Widget"},"number":{"type":"string","description":"Telefone da instância para contato"},"message":{"type":"string","description":"Mensagem que será apresenta no WhatsApp do cliente ao clicar no botão de Widget do seu site"},"label":{"type":"string","description":"Nome apresentado no Widget em seu site, ex.: Fale conosco"},"color":{"type":"string","description":"Cor do botão em hexadecimal, ex.: #089186"},"position":{"type":"string","description":"Posição do Widget"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const WidgetsGetwidgetbyid = {"body":{"type":"object","required":["instanceId","widgetId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"widgetId":{"type":"string","description":"Id do widget"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const WidgetsList = {"body":{"type":"object","required":["instanceId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
const WidgetsUpdate = {"body":{"type":"object","required":["instanceId","widgetId"],"properties":{"instanceId":{"type":"string","description":"Código da instância"},"widgetId":{"type":"string","description":"Id do Widget"},"name":{"type":"string","description":"Nome do Widget"},"message":{"type":"string","description":"Mensagem que será apresenta no WhatsApp do cliente ao clicar no botão de Widget do seu site"},"label":{"type":"string","description":"Nome apresentado no Widget em seu site, ex.: Fale conosco"},"color":{"type":"string","description":"Cor do botão em hexadecimal, ex.: #089186"},"position":{"type":"string","description":"Posição do Widget"}},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"instance-token":{"type":"string","$schema":"https://json-schema.org/draft/2020-12/schema#"}},"required":["instance-token"]}]},"response":{"200":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"},"400":{"type":"object","properties":{},"$schema":"https://json-schema.org/draft/2020-12/schema#"}}} as const
;
export { AssignLabel, CreateCopyCopy, DepartmentsCreate, DepartmentsGetdepartmentbyid, DepartmentsGetusersindepartment, DepartmentsList, EditUser, EndingsCreate, EndingsGetendingbyid, EndingsList, EndingsUpdate, GetAllUsersByInstance, GetOrCreateSessionByNumber, GetTemplates, GetUserById, HistoryReport, LeadsCreate, LeadsFindbyid, LeadsFindbyphonenumber, LeadsFindlabels, LeadsUpdate, MessagesGetall, MessagesReadmessages, MessagesSendcontact, MessagesSendfilefromurl, MessagesSendmessage, Register, SendTemplate, SessionsAssigndepartment, SessionsAssignto, SessionsFinish, SessionsGetsessionbyid, SessionsList, SessionsListfromlead, ShortcutsCreate, ShortcutsDelete, ShortcutsGetShortcutById, ShortcutsList, ShortcutsUpdate, TagsCreate, TagsGettagbyid, TagsListleadsbytag, TagsUpdate, UnassignLabel, UpdateOwner, WidgetsCreate, WidgetsGetwidgetbyid, WidgetsList, WidgetsUpdate }
